### ISSUE TITLE
First item doesn't save

### ISSUE THREAD

**Issue by mattl** [CreativeCommons-Seneca/qdp#1]
Same bug as in The List. Apparently I am bad at computers.

**Comment by robmyers** [comment]
Can't reproduce locally. Remake the DB and try again?

**Comment by rheaplex** [comment]
I think that the auth system intervenes.

Log in and register a work, the flow of communications goes:

```
save-work.php -> login.creativecommons.org/login?service=... -> save-work.php?ticket=... -> save-work.php
```

so the Form arguments are lost and $_POST is array(0) when we go to fetch 'uid' from it. Which doesn't work.

After this first round-trip, the flow goes:

```
save-work.php
```

So the post args aren't stripped.

**Comment by rheaplex** [comment]
Probably code more like this:

https://buildingtents.wordpress.com/2013/04/16/rpi-phpcas-authentication-tutorial/

**Comment by rheaplex** [comment]
Yep, a toy version based on that code is happy.

**Comment by rheaplex** [comment]
See pull request.
